global:
  scrape_interval: 15s 
  evaluation_interval: 15s 

# Regras de Alerta
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Regras de gravação 
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# Configurações de "scraping"
scrape_configs:
  - job_name: 'web_monitor_agent'
    static_configs:
      - targets: ['monitor_agent:8000']